<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/Linear_Algebra/LA_handson_by_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
M1=np.array([[12,14,16],[10,8,6],[3,4,5]])
M2=np.array([[1,4,6],[20,18,16],[12,13,14]])

In [2]:
M1+M2

array([[13, 18, 22],
       [30, 26, 22],
       [15, 17, 19]])

In [3]:
M1

array([[12, 14, 16],
       [10,  8,  6],
       [ 3,  4,  5]])

In [4]:
M2

array([[ 1,  4,  6],
       [20, 18, 16],
       [12, 13, 14]])

In [5]:
print(M1*M2)

[[ 12  56  96]
 [200 144  96]
 [ 36  52  70]]


In [6]:
print(M1/M2)

[[12.          3.5         2.66666667]
 [ 0.5         0.44444444  0.375     ]
 [ 0.25        0.30769231  0.35714286]]


In [7]:
print(M1-M2)

[[ 11  10  10]
 [-10 -10 -10]
 [ -9  -9  -9]]


In [8]:
np.invert(M1)

array([[-13, -15, -17],
       [-11,  -9,  -7],
       [ -4,  -5,  -6]])

In [9]:
np.matmul(M1, M2)

array([[484, 508, 520],
       [242, 262, 272],
       [143, 149, 152]])

In [10]:
np.dot(M1, M2)

array([[484, 508, 520],
       [242, 262, 272],
       [143, 149, 152]])

In [11]:
M1

array([[12, 14, 16],
       [10,  8,  6],
       [ 3,  4,  5]])

In [12]:
M1.T

array([[12, 10,  3],
       [14,  8,  4],
       [16,  6,  5]])

In [13]:
M1.transpose()

array([[12, 10,  3],
       [14,  8,  4],
       [16,  6,  5]])

In [17]:
((M1.T.T) == M1).all()

np.True_

In [18]:
A=np.array([[12,14],[10,8]])
B=np.array([[1,4],[20,16]])
x=(A+B).T
print(x)
y=A.T+B.T
print(y)

[[13 30]
 [18 24]]
[[13 30]
 [18 24]]


In [19]:
np.array_equal(M1,M2)

False

In [22]:
np.invert(M1)

array([[-13, -15, -17],
       [-11,  -9,  -7],
       [ -4,  -5,  -6]])

In [24]:
M1

array([[12, 14, 16],
       [10,  8,  6],
       [ 3,  4,  5]])

In [26]:
np.linalg.det(M2)

np.float64(-43.99999999999997)

In [27]:
np.linalg.inv(M2)

array([[-1.        , -0.5       ,  1.        ],
       [ 2.        ,  1.31818182, -2.36363636],
       [-1.        , -0.79545455,  1.40909091]])

In [28]:
np.invert(M2)

array([[ -2,  -5,  -7],
       [-21, -19, -17],
       [-13, -14, -15]])

In [29]:
A=np.array([[1,2],[2,4]])
eigVal,eigVec=np.linalg.eig(A)

In [34]:
A=np.array([[2,1],[1,2]])
eigVal,eigVec=np.linalg.eig(A)

In [35]:
eigVal

array([3., 1.])

In [36]:
eigVec

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])