<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/Linear_Algebra/Matrix_handson_by_Trainer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a matrix of size 3x3.perform the following opertion
1. Add 50 to your matrix
2. Subtract 20 in your matrix
3. Multiply 3 in your matrix
4. Divide you matrix by 4

In [ ]:
import numpy as np

In [ ]:
M1=np.random.randint(10,50,size=(3,3))
M1

array([[49, 36, 39],
       [11, 34, 23],
       [46, 22, 49]])

In [ ]:
#Add 50 to your matrix
M1+50

array([[99, 86, 89],
       [61, 84, 73],
       [96, 72, 99]])

In [ ]:
#Subtract 20 in your matrix
M1-20

array([[29, 16, 19],
       [-9, 14,  3],
       [26,  2, 29]])

In [ ]:
#Multiply 3 in your matrix
M1*3

array([[147, 108, 117],
       [ 33, 102,  69],
       [138,  66, 147]])

In [ ]:
#Divide you matrix by 4
M1/4

array([[12.25,  9.  ,  9.75],
       [ 2.75,  8.5 ,  5.75],
       [11.5 ,  5.5 , 12.25]])

# 2. Create two 3x3 matrix and then perform the addition,subtraction,multiplication and division bwtween there two matrices.

In [ ]:
M1=np.array([[12,14,16],[10,8,6],[3,4,5]])
M2=np.array([[1,4,6],[20,18,16],[12,13,14]])

In [ ]:
M1

array([[12, 14, 16],
       [10,  8,  6],
       [ 3,  4,  5]])

In [ ]:
M2

array([[ 1,  4,  6],
       [20, 18, 16],
       [12, 13, 14]])

In [ ]:
M1+M2

array([[13, 18, 22],
       [30, 26, 22],
       [15, 17, 19]])

In [ ]:
M1-M2

array([[ 11,  10,  10],
       [-10, -10, -10],
       [ -9,  -9,  -9]])

In [ ]:
M1*M2

array([[ 12,  56,  96],
       [200, 144,  96],
       [ 36,  52,  70]])

In [ ]:
M1/M2

array([[12.        ,  3.5       ,  2.66666667],
       [ 0.5       ,  0.44444444,  0.375     ],
       [ 0.25      ,  0.30769231,  0.35714286]])

# 3. Perform the dot product between two matrix of size(2x2).


In [ ]:
M1=np.array([[12,14],[10,8]])
M2=np.array([[1,4],[20,16]])

print(M1)
print()
print(M2)

[[12 14]
 [10  8]]

[[ 1  4]
 [20 16]]


In [ ]:
product=np.dot(M1,M2)
print(product)

[[292 272]
 [170 168]]


In [ ]:
M1 = np.random.randint(1,20,size=(3,3))
M1
M2 = np.random.randint(1,20,size=(3,3))
M1,M2

mat_dot = np.dot(M1,M2)
print("Dot Multiplication : \n", mat_dot)

Dot Multiplication : 
 [[ 29  93 309]
 [ 23  55 155]
 [ 70 254 427]]


# Transpose of a matrix

In [ ]:
M1=np.random.randint(10,50,size=(3,3))
M1

array([[20, 27, 16],
       [36, 31, 43],
       [39, 29, 40]])

In [ ]:
trans_M1=M1.T
trans_M1

array([[20, 36, 39],
       [27, 31, 29],
       [16, 43, 40]])

# Property 1: Transpose of a Transposed matrix is the original matrix

In [ ]:
trans_M1.T

array([[20, 27, 16],
       [36, 31, 43],
       [39, 29, 40]])

# Property 2: (A + B).T= A.T + B.T

In [ ]:
A=np.array([[12,14],[10,8]])
B=np.array([[1,4],[20,16]])

x=(A+B).T
print(x)
y=A.T+B.T
print(y)

[[13 30]
 [18 24]]
[[13 30]
 [18 24]]


# Property:3 (AxB).T=B.TxA.T

In [ ]:
A=np.array([[12,14],[10,8]])
B=np.array([[1,4],[20,16]])

x=np.dot(A,B).T
print(x)

y=B.T.dot(A.T)
print(y)

if np.array_equal(x,y):
  print('True')
else:
  print('false')

[[292 170]
 [272 168]]
[[292 170]
 [272 168]]
True


In [ ]:
# Determinant

In [ ]:
M1=np.random.randint(10,50,size=(3,3))
M1

array([[13, 22, 18],
       [28, 46, 44],
       [47, 12, 22]])

In [ ]:
np.linalg.det(M1)

np.float64(5368.000000000007)

In [ ]:
# Inverse
M1=np.array([[1,2],[3,4]])
M1

array([[1, 2],
       [3, 4]])

In [ ]:
# to find inverse this is the function
M1_inv=np.linalg.inv(M1)
M1_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Rank

In [ ]:
A=np.array([[1,2],[2,4]])
np.linalg.matrix_rank(A)

np.int64(1)

In [ ]:
A=np.array([[1,2],[5,9]])
np.linalg.matrix_rank(A)

np.int64(2)

# Eigen Values and Eigen Vectors

In [ ]:
A=np.array([[1,2],[2,4]])
eigVal,eigVec=np.linalg.eig(A)

In [ ]:
eigVal

array([0., 5.])

In [ ]:
eigVec

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])