<a href="https://colab.research.google.com/github/Kavia-M/Data_science_course-Intellipaat/blob/main/Python/Classwork/Trainers_notes/Modules/Handson/NumpyHandsOn_by_Trainer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tasks to be performed:

1. Create a numpy array with numpy.array module and with a data type integer and float.

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6], dtype="int")
arr2=np.array([10,50,30,25,60], dtype="float")

print(arr1, type(arr1))
print(arr2, type(arr2))

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[10. 50. 30. 25. 60.] <class 'numpy.ndarray'>


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2.dtype

dtype('float64')

2. Create numpy arrays that have zero, one, two, three, four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.

In [ ]:
arr0=np.array(10)
print("Array", arr0)
print("Dimension:",arr0.ndim)
print("Shape:",arr0.shape)

10
0
()


In [ ]:
arr1=np.array([1,2,3,4,5])
print("Array", arr1)
print("Dimension:",arr1.ndim)
print("Shape:",arr1.shape)

# (5) : integer 5
# (5,) : tuple with 5 elements

Array [1 2 3 4 5]
Dimension: 1
Shape: (5,)


In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print("Array \n", arr2)
print("Dimension:",arr2.ndim)
print("Shape:",arr2.shape)

Array 
 [[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)


In [ ]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print("Array \n", arr3)
print("Dimension:",arr3.ndim)
print("Shape:",arr3.shape)

Array 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
Dimension: 3
Shape: (1, 4, 3)


In [ ]:
arr4=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print("Array \n", arr4)
print("Dimension:",arr4.ndim)
print("Shape:",arr4.shape)

Array 
 [[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
Dimension: 4
Shape: (2, 1, 4, 3)


3.Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

USE: identity() or eye()

In [ ]:
print("\n",np.identity(2, dtype='int')) #2X2
print("\n",np.identity(3, dtype='int'))
print("\n",np.identity(4, dtype='int'))


 [[1 0]
 [0 1]]

 [[1 0 0]
 [0 1 0]
 [0 0 1]]

 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
np.eye(2,3, dtype='int') #eye: customize the matrix

array([[1, 0, 0],
       [0, 1, 0]])

In [ ]:
np.eye(N=10,M=10,k=-5, dtype="int")#k: controls which diagonal gets the 1s

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

4. Create a numpy array that has the shape 3x5 and all the elements are 5.

In [ ]:
np.full((3,5),5) #customized array, along with specific value

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.ones((3,5), dtype='int')*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.ones((3,5), dtype='int')+4

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.zeros((3,5), dtype='int')+5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
np.full(15, 5).reshape(3,5) #reshape: allows you to reshape the array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

5. Create a numpy array with random integers in the range 0-100, and the sample size should be 25.

In [ ]:
np.random.seed(42) #fix the sequence
arr1=np.random.randint(0,101, size=25)
print(arr1)
print(arr1.shape)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32]
(25,)


6. Create a random array, with the range 0-1000, with a size 50.

 Perform the following operations on the same.

a. Print the first ten elements of the array.

b. Print the last ten elements of the array.

c. Print the elements from the indexes 10-25.

d. Print the element at the index 22.

e. Print the array using negative indexing.

f. Print the last ten elements of the array, using negative indexing.

In [ ]:
np.random.seed(17)
a=np.random.randint(0,1001,size=50)
print(a)
print(a.shape)

[623 241 143 390 406 313 752 941 278  31 324 551 468 940 519 897 750  17
  41 696 778 482 643 831 262 987 166 987 809 697  30 273 237 229 433  32
 829 389 998 166   2  44 950 377 653 568 283 746 851 818]
(50,)


In [ ]:
#First 10 elements
print(a[:10])

[623 241 143 390 406 313 752 941 278  31]


In [ ]:
#Last 10 elements
print(a[40:])

[  2  44 950 377 653 568 283 746 851 818]


In [ ]:
#Elements from 10 to 25
print(a[10:26]) #end is excluded

[324 551 468 940 519 897 750  17  41 696 778 482 643 831 262 987]


In [ ]:
#Elements at index 22
print(a[22])

643


In [ ]:
#Array using negative indexing
print(a[::-1])

[818 851 746 283 568 653 377 950  44   2 166 998 389 829  32 433 229 237
 273  30 697 809 987 166 987 262 831 643 482 778 696  41  17 750 897 519
 940 468 551 324  31 278 941 752 313 406 390 143 241 623]


In [ ]:
#Last 10 elements using negative indexing
print(a[-50:])

[623 241 143 390 406 313 752 941 278  31 324 551 468 940 519 897 750  17
  41 696 778 482 643 831 262 987 166 987 809 697  30 273 237 229 433  32
 829 389 998 166   2  44 950 377 653 568 283 746 851 818]


7. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.

a. Insert the element 6 at the end of the array.

b. Insert the element 10 at the beginning of the array.

c. Insert the element 30, before 4.

d. Update the element 5 as 50.

e. Delete the element 50 in the updated array.

f. Create a function to search for the element 30.

g. Sort the array in ascending order